version: 2.1

orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0
  azure-cli: circleci/azure-cli@1.0.0
  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    working_directory: ~/bookmark-manager

    steps:
      # git pull
      - checkout

      # setup testing env
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # Download and cache dependencies
      - restore_cache:
          keys:
            - bookmark-manager-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: bookmark-manager-{{ checksum "pom.xml" }}

      # package into a jar
      - run: mvn clean package

      # build and push docker image to docker hub
      - run: mvn clean compile jib:build -Dimage=mosesjebish/bookmark-manager:$CIRCLE_BUILD_NUM

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: bookmark-manager
      - codecov/upload:
          file: ./target/jacoco.exec
          token: 17389c33-dcda-4c09-8087-9a82341add46